version: '3.8'

services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - medusa_network

  # Medusa Server
  # This service runs the Medusa backend application
  # and the admin dashboard.
  medusa:
    image: ${MEDUSA_IMAGE:-medusa-app:latest}
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
      FALLBACK_TO_SUPABASE: true
    env_file:
      - .env
    networks:
      - medusa_network

networks:
  medusa_network:
    driver: bridge
