version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: medusa_redis
    restart: unless-stopped
    networks:
      - medusa_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    # No port exposure - internal only

  medusa:
    image: ${MEDUSA_IMAGE:-ghcr.io/tembo-solutions/medusa-app:latest}
    container_name: medusa_backend
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    volumes:
      # Use named volumes to avoid mount issues and ensure uid 1001 ownership
      - uploads:/app/uploads
      - logs:/app/logs
    networks:
      - medusa_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  uploads:
    driver: local
  logs:
    driver: local

networks:
  medusa_network:
    driver: bridge
